obj-m := treiber.o
obj-m += treiber_classic.o
obj-m += openclose_normal.o
obj-m += openclose_atomic.o
obj-m += hello.o
obj-m += hello2.o
obj-m += zero.o
obj-m += null.o

obj-m += fifobuf.o
fifobuf-objs := buffer/fifo.o buf.o

obj-m += tasklet.o

