obj-m := treiber.o
obj-m += treiber_classic.o
obj-m += openclose_normal.o
obj-m += openclose_atomic.o
obj-m += hello.o
obj-m += hello2.o
obj-m += zero.o
obj-m += null.o

obj-m += mybuf.o
mybuf-y := buffer/fifo.o buf.o

obj-m += mybuf_threaded.o
mybuf_threaded-y := buffer/fifo_tsafe.o buf_threaded.o

obj-m += tasklet.o
obj-m += lock.o
obj-m += timer.o
obj-m += kthread.o
obj-m += wq.o
obj-m += open_once.o
