#!/bin/bash

install()
{
	compile
	copy
}

compile()
{
	make ARCH=arm CROSS_COMPILE=/opt/toolchains/Sourcery-CodeBench-ARM-2013.05/bin/arm-none-linux-gnueabi-
}

copy()
{
	cp *.ko ../../buildroot-2013.08.1/output/target/root
}

clean()
{
	rm -f *.ko *.o *.mod.c *.order *.symvers
}

command="$1"

if [ "$(type -t "$command")" == "function" ]
then
        echo "Running $command"

        $command
else
        echo "Unrecognized command." 1>&2
fi
