#!/bin/bash

compile()
{
	make ARCH=arm CROSS_COMPILE=/opt/toolchains/Sourcery-CodeBench-ARM-2013.05/bin/arm-none-linux-gnueabi-
}

copy()
{
	cp *.ko ../../buildroot-2013.08.1/output/target/root
}

command="$1"

if [ "$(type -t "$command")" == "function" ]
then
        echo "Running $command"

        $command
else
        echo "Unrecognized command." 1>&2
fi
